export const appointments = [
    {
      id: "1",
      name: "Bogdan Krivenchenko",
      age: 45,
      date: "12 April",
      time: "9:30",
      status: "declined",
      avatar: "",
    },
    {
      id: "2",
      name: "Jenny Wilson",
      age: 25,
      date: "Today",
      time: "10:30 AM",
      status: "confirmed",
      avatar: "",
    },
    {
      id: "3",
      name: "Dianne Russel",
      age: 45,
      date: "Today",
      time: "14:30 PM",
      status: "confirmed",
      avatar: "",
    },
    {
      id: "4",
      name: "Annette Black",
      age: 45,
      date: "Today",
      time: "14:30 PM",
      status: "declined",
      avatar: "",
    },
    {
      id: "5",
      name: "Annette Black",
      age: 45,
      date: "Today",
      time: "14:30 PM",
      status: "confirmed",
      avatar: "",
    },
    {
      id: "6",
      name: "Annette Black",
      age: 45,
      date: "Today",
      time: "14:30 PM",
      status: "pending",
      avatar: "",
    },
    {
      id: "7",
      name: "Annette Black",
      age: 45,
      date: "Today",
      time: "14:30 PM",
      status: "pending",
      avatar: "",
    },
  ]

export const patients = [
    {
      id: "1",
      name: "Deveon Lane",
      visitId: "OPD-2345",
      date: "5/7/21",
      gender: "Male",
      disease: "Diabetes",
      status: "Out-Patient",
      avatar: "",
    },
    {
      id: "2",
      name: "Albert Flores",
      visitId: "IPD-2424",
      date: "5/7/21",
      gender: "Male",
      disease: "Diabetes",
      status: "Out-Patient",
      avatar: "",
    },
    {
      id: "3",
      name: "Ella Lucia",
      visitId: "OPD-2345",
      date: "8/15/21",
      gender: "Male",
      disease: "Diabetes",
      status: "Out-Patient",
      avatar: "",
    },
    {
      id: "4",
      name: "Albert Flores",
      visitId: "IPD-2424",
      date: "8/30/21",
      gender: "Male",
      disease: "Diabetes",
      status: "Out-Patient",
      avatar: "",
    },
  ]

export const todayAppointments = [
    {
      id: "1",
      name: "Jhon Smith",
      specialty: "Clinic Consulting",
      status: "Ongoing",
      time: "",
      avatar: "",
    },
    {
      id: "2",
      name: "Frank Murray",
      specialty: "Vedio Consulting",
      status: "10:25",
      time: "10:25",
      avatar: "",
    },
    {
      id: "3",
      name: "Ella Lucia",
      specialty: "Emergency",
      status: "11:30",
      time: "11:30",
      avatar: "",
    },
    {
      id: "4",
      name: "Alyssa Dehm",
      specialty: "Clinic Consulting",
      status: "12:20",
      time: "12:20",
      avatar: "",
    },
  ]